
package com.uet.qpn.soaonce.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://webservice.pnq.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.pnq.webservice.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.GetAllBooksResponse")
    @Action(input = "http://webservice.pnq.com/WebService/getAllBooksRequest", output = "http://webservice.pnq.com/WebService/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.pnq.webservice.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByCode", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.GetBookByCode")
    @ResponseWrapper(localName = "getBookByCodeResponse", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.GetBookByCodeResponse")
    @Action(input = "http://webservice.pnq.com/WebService/getBookByCodeRequest", output = "http://webservice.pnq.com/WebService/getBookByCodeResponse")
    public Book getBookByCode(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBook", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.CreateBook")
    @ResponseWrapper(localName = "createBookResponse", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.CreateBookResponse")
    @Action(input = "http://webservice.pnq.com/WebService/createBookRequest", output = "http://webservice.pnq.com/WebService/createBookResponse")
    public boolean createBook(
            @WebParam(name = "arg0", targetNamespace = "")
                    Book arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBook", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.UpdateBook")
    @ResponseWrapper(localName = "updateBookResponse", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.UpdateBookResponse")
    @Action(input = "http://webservice.pnq.com/WebService/updateBookRequest", output = "http://webservice.pnq.com/WebService/updateBookResponse")
    public long updateBook(
            @WebParam(name = "arg0", targetNamespace = "")
                    Book arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBook", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.DeleteBook")
    @ResponseWrapper(localName = "deleteBookResponse", targetNamespace = "http://webservice.pnq.com/", className = "com.pnq.webservice.DeleteBookResponse")
    @Action(input = "http://webservice.pnq.com/WebService/deleteBookRequest", output = "http://webservice.pnq.com/WebService/deleteBookResponse")
    public boolean deleteBook(
            @WebParam(name = "arg0", targetNamespace = "")
                    Book arg0);

}
