
package com.uet.qpn.soaonce.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://webservice.pnq.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @return
     *     returns java.util.List<client.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://webservice.pnq.com/", className = "client.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://webservice.pnq.com/", className = "client.GetAllBooksResponse")
    @Action(input = "http://webservice.pnq.com/WebService/getAllBooksRequest", output = "http://webservice.pnq.com/WebService/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns client.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByCode", targetNamespace = "http://webservice.pnq.com/", className = "client.GetBookByCode")
    @ResponseWrapper(localName = "getBookByCodeResponse", targetNamespace = "http://webservice.pnq.com/", className = "client.GetBookByCodeResponse")
    @Action(input = "http://webservice.pnq.com/WebService/getBookByCodeRequest", output = "http://webservice.pnq.com/WebService/getBookByCodeResponse")
    public Book getBookByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
